<ul class="list-group">
    <?php foreach ($favouriteList as $list) { ?>
        <li class="list-group-item">
            <?php if (!empty($list['image'])) { ?>
                <img class="img-rounded"
                     src="<?php echo $this->escape($list['image']); ?>"
                     alt="<?php echo $this->escape($list['title']); ?>">
            <?php } ?>
            <a title="<?php echo $this->escape($list['title']); ?>"
               href="<?php echo $this->escape($list['url']); ?>">
                <?php echo $this->escape($list['title']); ?>
            </a>
        </li>
    <?php } ?>
    <br/>
</ul>