<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix row favourites">
    <div class="col-md-3">
        <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
    </div>
    <div class="col-md-9">
        <div class="page-header">
            <h1><?php echo $this->escape($title); ?></h1>
        </div>
        <?php if ($uid > 0) { ?>
            <div class="row favourite-box clearfix">
                <div class="col-md-3 col-md-offset-9">
                    <?php
                    $count = 0;
                    foreach ($favourites as $favourite) {
                        $count += $favourite['total_item'];
                    }
                    ?>
                    <div class="favourite-count">
                        <strong><i class="fas fa-check"></i> <?php _e('Favorites'); ?></strong>
                        : <?php echo _number($count); ?>
                    </div>

                </div>
            </div>
            <?php if (!empty($favourites)) { ?>
                <div class="card-heading">
                    <ul class="nav nav-tabs pi-card-tab-indicators">
                        <?php $first = true; ?>
                        <?php foreach ($favourites as $favourite) { ?>
                            <li class="nav-item">
                                <?php $first = false; ?>
                                <a aria-expanded="true" href="#" data-toggle="tab" class="nav-link <?php echo $first ? 'active' : '' ?> "
                                   data-target="#card-<?php echo $this->escape($favourite['name']); ?>">
                                    <?php echo $favourite['title']; ?>
                                </a>
                            </li>
                        <?php } ?>
                    </ul>
                </div>
                <div class=" pi-card-tab">
                    <div class="card-body tab-content">

                        <?php $first = true; ?>
                        <?php foreach ($favourites as $favourite) { ?>
                            <div class="tab-pane <?php echo $first ? 'active' : '' ?> "
                                 id="card-<?php echo $this->escape($favourite['name']); ?>">
                                <?php $first = false; ?>
                                <?php if (!empty($favourite['list'])) { ?>
                                    <?php
                                    $favouriteList = $favourite['list'];
                                    $favouriteName = $favourite['name'];
                                    $isProfil      = false;

                                    $partial = $this->templateModule('front/partial/favourite-list.phtml', $favourite['name']);
                                    if ($partial) {
                                    } else {
                                        $partial = $this->template('front/partial/favourite-list.phtml');
                                    }
                                    include $partial;
                                    ?>
                                    <div class="clearfix text-center">
                                        <a class="btn btn-success" title="<?php _e('Print'); ?>"
                                           href="<?php echo Pi::url($this->url('', ['controller' => 'print', 'action' => '', 'type' => $favouriteName])); ?>"
                                           target="_blank"><i
                                                    class="fas fa-print"></i> <?php _e('Print favourite list'); ?></a>
                                    </div>
                                <?php } else { ?>
                                    <div>
                                        <?php echo $this->escape($favourite['message']); ?>
                                    </div>
                                <?php } ?>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            <?php } else { ?>
                <div class="alert alert-danger" role="alert">
                    <h4><?php _e('There is no favorite to display'); ?></h4>
                    <p><?php _e('You have not yet used the favorite feature. Try it !'); ?></p>
                </div>
            <?php } ?>
        <?php } else { ?>
            <div class="alert alert-danger" role="alert">
                <h4><?php _e('You dont have access to this area - Permission denied'); ?></h4>
                <p><?php _e('You have to login first to be able to manage your favorites'); ?></p>
            </div>
        <?php } ?>
    </div>
</div>