<?php if (empty($favourite)) {
    return;
} ?>
<?php
// Load language file
Pi::service('i18n')->load(array('module/favourite', 'default'));
// Load jQuery
$this->jQuery();
// Load js files
$this->js($this->assetModule('script/favourite.min.js', 'favourite'));
// Load css files
$this->css($this->assetModule('script/favourite.css', 'favourite'));
// Set html id
$favourite['htmlId'] = sprintf('favourite-%s-%s-%s', $favourite['module'], $favourite['table'], $favourite['item']);
// Set icon
$configFavourite = Pi::service('registry')->config->read('favourite', 'favourite');
switch ($configFavourite['favourite_icon']) {
    case 'wishlist':
        $favourite['icon'] = ($favourite['is']) ? 'fa-heart' : 'fa-heart-o';
        $favourite['iconbar'] = 'wishlist';
        $favourite['iconclass'] = 'favouritebar-click btn btn-default';
        break;

    case 'bookmark':
        $favourite['icon'] = ($favourite['is']) ? 'fa-bookmark' : 'fa-bookmark-o';
        $favourite['iconbar'] = 'bookmark';
        $favourite['iconclass'] = 'favouritebar-click';
        break;

    case 'heart':
        $favourite['icon'] = ($favourite['is']) ? 'fa-heart' : 'fa-heart-o';
        $favourite['iconbar'] = 'heart';
        $favourite['iconclass'] = 'favouritebar-click';
        break;

    case 'star':
    default:
        $favourite['icon'] = ($favourite['is']) ? 'fa-star' : 'fa-star-o';
        $favourite['iconbar'] = 'star';
        $favourite['iconclass'] = 'favouritebar-click';
        break;
}
// Set class
$favouriteClass = isset($favourite['class']) ? $favourite['class'] : '';
// Set tooltip text
$favourite['tooltip'] = ($favourite['is']) ? __('Remove favourite') : __('Declare as favourite');
// Set js
$js = <<<'EOT'
$("#%s").tooltip();
EOT;
$js = sprintf($js, $favourite['htmlId']);
$this->footScript()->appendScript($js);
// Set onclick
$onclick = <<<'EOT'
setFavourite('%s', '%s', '%s', '%s', '%s');
EOT;
$onclick = sprintf($onclick,
    Pi::url('favourite', true),
    $favourite['item'],
    $favourite['table'],
    $favourite['module'],
    $favourite['iconbar']
);
?>
<div class="favouritebar <?php echo $favouriteClass; ?>">
    <a class="<?php echo $favourite['iconclass']; ?>" data-toggle="tooltip" data-placement="top" title="<?php echo $favourite['tooltip']; ?>"
       id="<?php echo $favourite['htmlId']; ?>" onclick="<?php echo $onclick; ?>">
        <i class="fa <?php echo $favourite['icon']; ?>"></i>
        <?php if ($configFavourite['favourite_icon'] == 'wishlist') {
            echo __('Wishlist');
        } ?>
    </a>
    <?php if ($configFavourite['favourite_view_count'] && isset($favorite['count']) && $favorite['count']) { ?>
        <div class="favorite-count">
            <span class="label label-default"><?php echo _number($favorite['count']); ?></span>
        </div>
    <?php } ?>
</div>