<div class="clearfix">
    <div class="page-header">
        <h1><?php echo $this->escape($title); ?></h1>
    </div>
    <?php if ($uid > 0) { ?>
    <?php if (!empty($favourites)) { ?>
    <div class"well"><?php _e('You will find below the list of items you picked up as favorite, for later usage '); ?></div>
    <div class="panel panel-default pi-panel-tab">
        <div class="panel-heading">
        	<ul class="pi-panel-tab-indicators">
        		<?php foreach ($favourites as $favourite) { ?>
        		<li<?php if ($favourite['name'] == 'news') { echo ' class="active"'; } ?>>
        			<a aria-expanded="true" href="#" data-toggle="tab" data-target="#panel-<?php echo $favourite['name']; ?>"><?php echo $favourite['title']; ?></a>
        		</li>
        		<?php } ?>
        	</ul>
        </div>
        <div class="panel-body tab-content">
        	<?php foreach ($favourites as $favourite) { ?>
        	<div class="tab-pane<?php if ($favourite['name'] == 'news') { echo ' active'; } ?>" id="panel-<?php echo $favourite['name']; ?>">
        		<div class="well">
                    <h2><?php echo $favourite['title']; ?></h2>
                    <?php echo $favourite['message']; ?>
                </div>
        	</div>
        	<?php } ?>
        </div>
    </div> 
    <?php } else { ?>
    <div class="alert alert-danger" role="alert">
    	<h4><?php _e('There is no favorite to display'); ?></h4>
    	<p><?php _e('You have not yet used the favorite feature. Try it !'); ?></p>
    </div>
    <?php } ?>
    <?php } else { ?>
    <div class="alert alert-danger" role="alert">
    	<h4><?php _e('You dont have access to this area - Permission denied'); ?></h4>
    	<p><?php _e('You have to login first to be able to manage your favorites'); ?></p>
    </div>
    <?php } ?>
</div>