<?php
// Load css files
$this->css(array($this->assetModule('css/front.css', 'favourite') => array('defer' => 'defer')));
$this->css(array($this->assetModule('script/favourite.css', 'favourite') => array('defer' => 'defer')));
?>

<?php if (empty($favourite)) {
    return;
} ?>
<?php
$currentUser = false;

$avatar = Pi::service('user')->avatar(null, 'small', [
    'alt'   => $currentUser['name'],
    'class' => 'rounded-circle',
]);

if (Pi::service('user')) {
    $currentUser = Pi::user()->get(Pi::service('user')->getId(), [
        'id', 'identity', 'name',
    ]);

    if ($currentUser) {
        $currentUser['profileUrl'] = Pi::url(Pi::service('user')->getUrl('profile', [
            'id' => $currentUser['id'],
        ]));
    }

    $avatar = Pi::service('user')->avatar(Pi::service('user')->getId(), 'small', [
        'alt'   => $currentUser['name'],
        'class' => 'rounded-circle',
    ]);

    $isLiked = false;
    if (isset($favouriteList)) {
        foreach ($favouriteList as $user) {
            if (isset($user['id']) && isset($currentUser['id']) && $user['id'] == $currentUser['id']) {
                $isLiked = true;
            }
        }
    }
}

// Load language file
Pi::service('i18n')->load(['module/favourite', 'default']);
// Set icon
$configFavourite = Pi::service('registry')->config->read('favourite', 'favourite');
switch ($configFavourite['favourite_icon']) {
    case 'wishlist':
        $favourite['icon']      = ($favourite['is']) ? 'fas fa-check' : '';
        $favourite['iconbar']   = ($favourite['is']) ? __('Add to Wishlist ?') : __('Whishlist !');
        $favourite['iconclass'] = ($favourite['is']) ? 'favouritebar-btn btn btn-success' : 'favouritebar-btn btn btn-primary';
        break;

    case 'bookmark':
        $favourite['icon']      = ($favourite['is']) ? 'fas fa-bookmark' : 'far fa-bookmark';
        $favourite['iconbar']   = 'bookmark';
        $favourite['iconclass'] = 'favouritebar-icon';
        break;

    case 'heart':
        $favourite['icon']      = ($favourite['is']) ? 'fas fa-heart' : 'far fa-heart';
        $favourite['iconbar']   = 'heart';
        $favourite['iconclass'] = 'favouritebar-icon';
        break;

    case 'star':
    default:
        $favourite['icon']      = ($favourite['is']) ? 'fas fa-star' : 'far fa-star';
        $favourite['iconbar']   = 'star';
        $favourite['iconclass'] = 'favouritebar-icon';
        break;
}
// Set html id
$favourite['htmlId'] = sprintf('favourite-%s-%s-%s', $favourite['module'], $favourite['table'], $favourite['item']);
// Set class
$favouriteClass = isset($favourite['class']) ? $favourite['class'] : '';
// Set tooltip text
$favourite['tooltip'] = ($favourite['is']) ? __('Remove favourite') : __('Declare as favourite');
// Load jQuery
$this->jQuery();
// Load js files
if ($configFavourite['favourite_icon'] == 'wishlist') {
    $this->js($this->assetModule('script/favourite.wishlist.js', 'favourite'), array('defer' => 'defer'));
} else {
    $this->js($this->assetModule('script/favourite.js', 'favourite'), array('defer' => 'defer'));
}

/**
 * AJAX MODE
 */
if(!empty($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest')
{
    /** @var Pi\View\Helper\HeadScript $headScript */
    $headScript = $this->plugin('headScript');
    foreach($headScript as $head){
        if(preg_match('#module-favourite#', $head->attributes['src'])){
            echo '<script src="'.$head->attributes['src'].'"></script>';
        }
    }

    echo $this->plugin('headLink');
    echo $this->plugin('footScript');
}


// Set onclick
$onclick
         = <<<'EOT'
setFavourite('%s', '%s', '%s', '%s', '%s', '%s', '%s');
EOT;
$onclick = sprintf($onclick,
    Pi::url('favourite', true),
    $favourite['item'],
    $favourite['table'],
    $favourite['module'],
    $favourite['iconbar'],
    Pi::user()->config('enable_modal') ? 'true' : 'false',
    str_replace("'", "\'", __('Login / Register'))
);
?>

<div class="favouritebar text-center <?php echo $favouriteClass; ?>">
    <a class="<?php echo $favourite['iconclass']; ?>"
       rel="nofollow"
       title="<?php echo $favourite['tooltip']; ?>"
       id="<?php echo $favourite['htmlId']; ?>"
        <?php if (Pi::user()->getId() || !Pi::user()->config('enable_modal')) { ?>
            data-toggle="tooltip" data-placement="top"
            onclick="<?php echo $onclick; ?>"
        <?php } else { ?>
            data-action="login" data-toggle="modal" data-target="#loginRegisterModal"
        <?php } ?>>

        <?php if ($favourite['icon']) { ?>
            <i class="<?php echo $favourite['icon']; ?>"></i>
        <?php } ?>
        <?php if ($configFavourite['favourite_icon'] == 'wishlist') {
            echo ($favourite['is']) ? __('Whishlist !') : __('Add to Wishlist ?');
        } ?>
    </a>
    <?php if ($configFavourite['favourite_view_count'] && isset($favorite['count']) && $favorite['count']) { ?>
        <div class="favorite-count">
            <span class="badge badge-default"><?php echo _number($favorite['count']); ?></span>
        </div>
    <?php } ?>
</div>
<?php if (isset($favouriteList)) { ?>
    <ul class="list-inline itemUserActivityItem text-center">
        <?php if (!$currentUser) : ?>
            <li class="list-inline-item itemUserActivityUser liked hide">
                <?php echo $avatar; ?>
            </li>
        <?php endif; ?>
        <?php if ($currentUser && !$isLiked) : ?>
            <li class="list-inline-item itemUserActivityUser liked hide">
                <a title="<?php echo $currentUser['name']; ?>"
                   href="<?php echo isset($currentUser['profileUrl']) ? $currentUser['profileUrl'] : '#'; ?>">
                    <?php echo $avatar; ?>
                </a>
            </li>
        <?php endif; ?>

        <?php $i = 1; ?>
        <?php foreach ($favouriteList as $user) { ?>
            <?php if ($i < 3) { ?>
                <li class="list-inline-item itemUserActivityUser <?php if ($currentUser && isset($user['id']) && isset($currentUser['id']) && $user['id'] == $currentUser['id']) : ?>liked<?php endif; ?>">
                    <a title="<?php echo isset($user['name']) ? $user['name'] : ''; ?>"
                       href="<?php echo $user['profileUrl']; ?>">
                        <?php echo $user['avatar']; ?>
                    </a>
                </li>
                <?php $i++; ?>
            <?php } ?>
        <?php } ?>
        <li class="list-inline-item itemUserActivityMore <?php if (count($favouriteList) <= 2) { ?>hide<?php } ?>">
            <div data-toggle="modal" data-target="#favouriteModal">
                ...
            </div>
        </li>
    </ul>
<?php } ?>
    