<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix row favourites">
    <div class="col-md-3">
        <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
    </div>
    <div class="col-md-9">
        <div class="page-header">
            <h1><?php echo $this->escape($title); ?></h1>
        </div>
        <?php if ($uid > 0) { ?>
            <div class="row favourite-box">
                <div class="col-md-9">
    
                    <div class="favourite-avatar pull-left"><?php echo $user['avatar']; ?></div>
                    <div class="favourite-text pull-left">
                        <h2>
                            <a title="<?php echo $user['name']; ?>" href="<?php echo $user['profileUrl']; ?>">
                                <?php echo $user['name']; ?>
                            </a>
                        </h2>
                    </div>
                </div>
                <div class="col-md-3">
                    <?php 
                        $count = 0;
                        foreach ($favourites as $favourite) {
                            $count += count($favourite['list']);
                        }
                    ?>
                    <div class="favourite-count">
                        <strong><i class="fa fa-check"></i> <?php _e('Favorites'); ?></strong> : <?php echo _number($count); ?>
                    </div>
                   
                </div>
            </div>
            <?php if (!empty($favourites)) { ?>
                <div class="well">
                    <?php _e('You will find below the list of items you picked up as favorite, for later usage '); ?>
                </div>
                 <div class="panel-heading">
                    <ul class="nav nav-tabs pi-panel-tab-indicators">
                        <?php $first = true; ?>
                        <?php foreach ($favourites as $favourite) { ?>
                            <li class="<?php echo $first ? 'active' : '' ?>">
                                <?php $first = false; ?>
                                <a aria-expanded="true" href="#" data-toggle="tab"
                                   data-target="#panel-<?php echo $this->escape($favourite['name']); ?>">
                                    <?php echo $this->escape($favourite['title']); ?>
                                </a>
                            </li>
                        <?php } ?>
                    </ul>
                </div>
                <div class=" pi-panel-tab">
                    <div class="panel-body tab-content">
                        
                        <?php $first = true; ?>
                        <?php foreach ($favourites as $favourite) { ?>
                                <div class="tab-pane <?php echo $first ? 'active' : '' ?> " id="panel-<?php echo $this->escape($favourite['name']); ?>">
                                <?php $first = false; ?>
                                <?php if (!empty($favourite['list'])) { ?>
                                    <?php
                                        $favouriteList = $favourite['list'];
                                        $partial = $this->templateModule('front/partial/favourite-list.phtml',  $favourite['name']);
                                        if ($partial) {
                                        } else {
                                            $partial = $this->template('front/partial/favourite-list.phtml');
                                        }
                                        include $partial;
                                    ?>
                                <div class="clearfix text-center">
                                    <a class="btn btn-success" title="<?php _e('Print'); ?>" href="<?php echo Pi::url($this->url('', array('controller' => 'print', 'action' => '', 'type' => $favourite['name'] ))); ?>"
                                       target="_blank"><i class="fa fa-print"></i> <?php _e('Print favourite list'); ?></a>
                                </div>
                                <?php } else { ?>
                                    <div class="well">
                                        <?php echo $this->escape($favourite['message']); ?>
                                    </div>
                                <?php } ?>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            <?php } else { ?>
                <div class="alert alert-danger" role="alert">
                    <h4><?php _e('There is no favorite to display'); ?></h4>
                    <p><?php _e('You have not yet used the favorite feature. Try it !'); ?></p>
                </div>
            <?php } ?>
        <?php } else { ?>
            <div class="alert alert-danger" role="alert">
                <h4><?php _e('You dont have access to this area - Permission denied'); ?></h4>
                <p><?php _e('You have to login first to be able to manage your favorites'); ?></p>
            </div>
        <?php } ?>
    </div>
</div>